### ISSUE TITLE
VR marker model may fail to load

### ISSUE THREAD

**Issue by dabeshouse** [TheAliceProject/alice3#395]
There are reports in Jira of the model failing to load its texture and thereby reporting a red queen.

This is seen when starting a new VR world and the marker support is being set up.

```java
java.lang.AssertionError: edu.cmu.cs.dennisc.scenegraph.SkeletonVisual$2[owner=SkeletonVisual[name="null"];name=textures]
	at edu.cmu.cs.dennisc.property.CopyableArrayProperty.setValue(CopyableArrayProperty.java:64)
	at org.lgna.story.implementation.alice.JointImplementationAndVisualDataFactory$VisualData.<init>(JointImplementationAndVisualDataFactory.java:80)
	at org.lgna.story.implementation.alice.JointImplementationAndVisualDataFactory.createVisualData(JointImplementationAndVisualDataFactory.java:238)
	at org.lgna.story.implementation.PerspectiveCameraMarkerImp.createVRVisual(PerspectiveCameraMarkerImp.java:112)
	at org.lgna.story.implementation.PerspectiveCameraMarkerImp.initialize(PerspectiveCameraMarkerImp.java:104)
	at org.lgna.story.implementation.PerspectiveCameraMarkerImp.createVisuals(PerspectiveCameraMarkerImp.java:93)
	at org.lgna.story.implementation.MarkerImp.<init>(MarkerImp.java:63)
	at org.lgna.story.implementation.CameraMarkerImp.<init>(CameraMarkerImp.java:53)
	at org.lgna.story.implementation.PerspectiveCameraMarkerImp.<init>(PerspectiveCameraMarkerImp.java:83)
	at org.lgna.story.PerspectiveCameraMarker.<init>(PerspectiveCameraMarker.java:51)
	at org.alice.stageide.sceneeditor.viewmanager.CameraMarkerTracker$PerspectiveCameraMarkerConfiguration.<init>(CameraMarkerTracker.java:296)
	at org.alice.stageide.sceneeditor.viewmanager.CameraMarkerTracker$StartingCameraMarkerConfiguration.<init>(CameraMarkerTracker.java:325)
	at org.alice.stageide.sceneeditor.viewmanager.CameraMarkerTracker.initializeCameraMarkers(CameraMarkerTracker.java:144)
	at org.alice.stageide.sceneeditor.viewmanager.CameraMarkerTracker.<init>(CameraMarkerTracker.java:96)
	at org.alice.stageide.sceneeditor.StorytellingSceneEditor.initializeComponents(StorytellingSceneEditor.java:718)
	at org.alice.ide.sceneeditor.AbstractSceneEditor.initializeIfNecessary(AbstractSceneEditor.java:156)
	at org.alice.ide.sceneeditor.AbstractSceneEditor.setActiveScene(AbstractSceneEditor.java:352)
	at org.alice.stageide.sceneeditor.StorytellingSceneEditor.setActiveScene(StorytellingSceneEditor.java:765)
	at org.alice.ide.sceneeditor.AbstractSceneEditor$2.valueChanged(AbstractSceneEditor.java:114)
	at org.lgna.croquet.State.addAndInvokeNewSchoolValueListener(State.java:124)
	at org.alice.ide.sceneeditor.AbstractSceneEditor.setProgramType(AbstractSceneEditor.java:400)
	at org.alice.ide.sceneeditor.AbstractSceneEditor.handleProjectOpened(AbstractSceneEditor.java:405)
	at org.alice.stageide.sceneeditor.StorytellingSceneEditor.handleProjectOpened(StorytellingSceneEditor.java:1164)
	at org.alice.ide.sceneeditor.AbstractSceneEditor$1.changed(AbstractSceneEditor.java:106)
	at org.alice.ide.sceneeditor.AbstractSceneEditor$1.changed(AbstractSceneEditor.java:99)
	at org.alice.ide.sceneeditor.AbstractSceneEditor.handleAddedTo(AbstractSceneEditor.java:422)
	at org.lgna.croquet.views.AwtComponentView.handleParentChange(AwtComponentView.java:171)
	at org.lgna.croquet.views.AwtComponentView.handleHierarchyChanged(AwtComponentView.java:189)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
	at java.desktop/java.awt.Container.addImpl(Container.java:1170)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at org.lgna.croquet.views.AwtContainerView.internalAddComponent(AwtContainerView.java:135)
	at org.lgna.croquet.views.BorderPanel.addComponent(BorderPanel.java:183)
	at org.lgna.croquet.views.BorderPanel.addCenterComponent(BorderPanel.java:187)
	at org.alice.ide.sceneeditor.SceneComposite.handlePreActivation(SceneComposite.java:70)
	at org.lgna.croquet.CardOwnerComposite.showCard(CardOwnerComposite.java:157)
	at org.lgna.croquet.CardOwnerComposite.showCard(CardOwnerComposite.java:164)
	at org.alice.stageide.perspectives.code.CodeContextSplitComposite.handleTypeStateChanged(CodeContextSplitComposite.java:106)
	at org.alice.stageide.perspectives.code.CodeContextSplitComposite$1.valueChanged(CodeContextSplitComposite.java:162)
	at org.lgna.croquet.meta.MetaState.checkValueAndFireIfAppropriate(MetaState.java:86)
	at org.lgna.croquet.meta.StateTrackingMetaState$1.valueChanged(StateTrackingMetaState.java:70)
	at org.lgna.croquet.State.fireChanged(State.java:147)
	at org.lgna.croquet.ItemState.fireChanged(ItemState.java:253)
	at org.lgna.croquet.TabState.fireChanged(TabState.java:78)
	at org.lgna.croquet.TabState.fireChanged(TabState.java:55)
	at org.lgna.croquet.State.commitFinalValue(State.java:220)
	at org.lgna.croquet.State.lambda$changeValueFromSwing$1(State.java:240)
	at org.lgna.croquet.State.changeModelValue(State.java:205)
	at org.lgna.croquet.State.changeValueFromSwing(State.java:240)
	at org.lgna.croquet.State.changingValueFromSwing(State.java:234)
	at org.lgna.croquet.SingleSelectListState$2.valueChanged(SingleSelectListState.java:502)
	at org.lgna.croquet.imp.liststate.SingleSelectListStateSwingModel.fireListSelectionChanged(SingleSelectListStateSwingModel.java:88)
	at org.lgna.croquet.SingleSelectListState.setSwingValue(SingleSelectListState.java:220)
	at org.lgna.croquet.State.changeValue(State.java:189)
	at org.lgna.croquet.SingleSelectListState.changeValue(SingleSelectListState.java:245)
	at org.lgna.croquet.State.changeValue(State.java:184)
	at org.lgna.croquet.State.setValueTransactionlessly(State.java:248)
	at org.alice.stageide.StageIDE.setProject(StageIDE.java:435)
	at org.alice.ide.ProjectApplication.updateInterface(ProjectApplication.java:394)
	at org.alice.ide.ProjectApplication.projectLoaded(ProjectApplication.java:366)
	at org.alice.ide.ProjectApplication.lambda$loadProject$0(ProjectApplication.java:356)
	at org.alice.ide.uricontent.UriContentLoader$Worker.lambda$acceptOnEventDispatchThread$0(UriContentLoader.java:83)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by dabeshouse** [comment]
Reported 65 times against Windows 10 and Mac OS X

**Comment by dabeshouse** [comment]
How concerning is this?
