### ISSUE TITLE
An error has occured during startup

### ISSUE THREAD

**Issue by pikriawan** [TheAliceProject/alice3#416]
```
java.lang.UnsatisfiedLinkError: /opt/alice3/platform/linux-amd64/jogl/natives/linux-amd64/libgluegen_rt.so: /opt/alice3/platform/linux-amd64/jogl/natives/linux-amd64/libgluegen_rt.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at edu.cmu.cs.dennisc.java.lang.SystemUtilities.loadLibrary(SystemUtilities.java:220)
	at edu.cmu.cs.dennisc.render.gl.RendererNativeLibraryLoader$1.loadLibrary(RendererNativeLibraryLoader.java:75)
	at edu.cmu.cs.dennisc.render.gl.RendererNativeLibraryLoader$1.loadLibrary(RendererNativeLibraryLoader.java:94)
	at edu.cmu.cs.dennisc.render.gl.RendererNativeLibraryLoader$1.loadLibrary(RendererNativeLibraryLoader.java:105)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at edu.cmu.cs.dennisc.render.gl.RendererNativeLibraryLoader.initializeIfNecessary(RendererNativeLibraryLoader.java:121)
	at edu.cmu.cs.dennisc.render.gl.GlrRenderFactory.<clinit>(GlrRenderFactory.java:74)
	at edu.cmu.cs.dennisc.render.RenderUtils.getDefaultRenderFactory(RenderUtils.java:52)
	at org.alice.stageide.EntryPoint.main(EntryPoint.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
	at install4j.org.alice.stageide.EntryPoint.main(Unknown Source)
```

**Comment by dabeshouse** [comment]
Which Linux are you running?
How did you install Alice?
I think this is 3.9, but can you verify that?

Hopefully we can get things sorted out.

**Comment by pikriawan** [comment]
I use Debian (bookworm) with arm64 architecture.
I installed Alice 3 using .deb installer with `sudo apt install ./alice3_linux_bundle_3_9_0_0.deb` command.
